version: "2"
plugins:
  pep8:
    enabled: true
  bandit:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  editorconfig:
    enabled: true
    channel: beta
  fixme:
    enabled: true
exclude_patterns:
  - tests/
