stages:
  - test
  - build
  - verifybuild

.test_template: &test_template
  stage: test
  before_script:
    - pip install -U pip
    - pip install -U -r requirements_dev.txt
  tags:
    - normal
  
python3:
  <<: *test_template
  image: python:3-slim
  script:
    - pytest

python flake:
  <<: *test_template 
  image: python:3-slim
  script:
    - tox -e flake8

python 35:
  <<: *test_template
  image: python:3.5
  script:
    - tox -e py35

python 36:
  <<: *test_template
  image: python:3.6
  script:
    - tox -e py36

python 37:
  <<: *test_template
  image: python:3.7
  script:
    - tox -e py37

python 38:
  <<: *test_template
  image: python:3.8
  script:
    - tox -e py38


.build_docker_image_template: &build_docker_image_template
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t gitlab.askanna.io:4567/askanna/askanna-cli:$CI_COMMIT_REF_NAME .
    - docker push gitlab.askanna.io:4567/askanna/askanna-cli:$CI_COMMIT_REF_NAME
  except:
    - triggers
    - schedules
    - branches

build_docker_image_version:
  <<: *build_docker_image_template
  only:
    - /v*.*.*/

build_docker_image_master:
  <<: *build_docker_image_template
  except:
    - triggers
  only:
    - master

verify_docker_build:
  stage: verifybuild
  image: gitlab.askanna.io:4567/askanna/askanna-cli:$CI_COMMIT_REF_NAME
  tags:
    - normal
  script:
    - askanna
  only:
    - master
    - /v*.*.*/