stages:
  - test

.test_template: &test_template
  stage: test
  before_script:
    - pip install -U pip
    - pip install -U -r requirements_dev.txt
  tags:
    - normal
  
python3:
  <<: *test_template
  image: python:3-slim
  script:
    - pytest

python flake:
  <<: *test_template 
  image: python:3-slim
  script:
    - tox -e flake8

python lint:
  <<: *test_template
  image: python:3-slim
  script:
    - flake8 askanna_cli tests
  allow_failure: true

python 35:
  <<: *test_template
  image: python:3.5
  script:
    - tox -e py35

python 36:
  <<: *test_template
  image: python:3.6
  script:
    - tox -e py36

python 37:
  <<: *test_template
  image: python:3.7
  script:
    - tox -e py37

python 38:
  <<: *test_template
  image: python:3.8
  script:
    - tox -e py38
