tasks:
  - init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements-dev.txt
      pip install --editable .
      mkdir .vscode && ln -n .gitpod-vscode-settings.json .vscode/settings.json
    command: |
      source .venv/bin/activate
      pre-commit install --install-hooks

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - eamodio.gitlens
    - GitLab.gitlab-workflow
    - ms-python.python
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - timonwong.shellcheck
    - ZainChen.json
    - ms-vscode.makefile-tools
