stages:
  - test
  - build
  - verifybuild

.test_template: &test_template
  stage: test
  before_script:
    - pip install -U pip
    - pip install -U -r requirements_dev.txt
  tags:
    - kubernetes

python3:
  <<: *test_template
  image: python:3-slim
  script:
    - pytest

python flake:
  <<: *test_template 
  image: python:3-slim
  script:
    - tox -e flake8

python lint:
  <<: *test_template
  image: python:3-slim
  script:
    - flake8 askanna_cli tests
  allow_failure: true

python 35:
  <<: *test_template
  image: python:3.5
  script:
    - tox -e py35

python 36:
  <<: *test_template
  image: python:3.6
  script:
    - tox -e py36

python 37:
  <<: *test_template
  image: python:3.7
  script:
    - tox -e py37

python 38:
  <<: *test_template
  image: python:3.8
  script:
    - tox -e py38

python 39:
  <<: *test_template
  image: python:3.9-rc-buster
  script:
    - tox -e py39

.build_docker_image_template: &build_docker_image_template
  image: docker:git
  stage: build
  tags:
    - docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    PY_VERSION: "3-slim"
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${CI_REGISTRY}/askanna/askanna-cli:${PY_VERSION}-${CI_COMMIT_REF_NAME} --build-arg PY_VERSION=${PY_VERSION} .
    - docker push ${CI_REGISTRY}/askanna/askanna-cli:${PY_VERSION}-${CI_COMMIT_REF_NAME}
  except:
    - triggers
    - schedules
    - branches

build_docker_image_version:
  <<: *build_docker_image_template
  only:
    refs:
      - /v*.*.*/

build_docker_image_master:
  <<: *build_docker_image_template
  except:
    - triggers
  only:
    refs:
      - master

verify_docker_build:
  stage: verifybuild
  variables:
    PY_VERSION: "3-slim"
  image: ${CI_REGISTRY}/askanna/askanna-cli:${PY_VERSION}-${CI_COMMIT_REF_NAME}
  tags:
    - kubernetes
  script:
    - askanna
  only:
    refs:
      - master

image_py35:
  <<: *build_docker_image_template
  variables:
    DOCKER_TLS_CERTDIR: ""
    PY_VERSION: "3.5-slim"
  except:
    - triggers
  only:
    refs:
      - master

image_py36:
  <<: *build_docker_image_template
  variables:
    DOCKER_TLS_CERTDIR: ""
    PY_VERSION: "3.6-slim"
  except:
    - triggers
  only:
    refs:
      - master

image_py37:
  <<: *build_docker_image_template
  variables:
    DOCKER_TLS_CERTDIR: ""
    PY_VERSION: "3.7-slim"
  except:
    - triggers
  only:
    refs:
      - master

image_py38:
  <<: *build_docker_image_template
  variables:
    DOCKER_TLS_CERTDIR: ""
    PY_VERSION: "3.8-slim"
  except:
    - triggers
  only:
    refs:
      - master

image_py39:
  <<: *build_docker_image_template
  variables:
    DOCKER_TLS_CERTDIR: ""
    PY_VERSION: "3.9-rc-buster"
  except:
    - triggers
  only:
    refs:
      - master
