repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
      - id: end-of-file-fixer

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.0
    hooks:
      - id: markdownlint

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          [
            "--config=setup.cfg",
            "--ignore=W391,W503,E203",
            "--max-line-length=119",
          ]

  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        args: ["--line-length=119"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        args: [--configfile, pyproject.toml]
